/**
 * SL1/SL1S slice exporter for Prusa SL1 / SL1S printers.
 *
 * Format: ZIP archive containing:
 *   - PNG layer images (named NNNNN.png)
 *   - prusaslicer.ini (slicer settings)
 *   - config.ini (print config with exposure, lift, layer count)
 */
import type {
  SliceExporter,
  LayerSource,
  SliceSettings,
  ProgressCallback,
} from '@core/format-registry';
import type { PrinterSpec } from '@core/types';

function buildConfigIni(settings: SliceSettings, layerCount: number): string {
  const lines: string[] = [
    '# Generated by SliceLab',
    `expTime = ${settings.normalExposure}`,
    `expTimeFirst = ${settings.bottomExposure}`,
    `numFade = ${settings.bottomLayers}`,
    `numFast = ${layerCount - settings.bottomLayers}`,
    `numSlow = ${settings.bottomLayers}`,
    `layerHeight = ${settings.layerHeight}`,
    `usedMaterial = ${settings.totalVolumeMm3 !== undefined ? (settings.totalVolumeMm3 / 1000).toFixed(2) : '0'}`,
    `printTime = 0`,
    '',
  ];
  return lines.join('\n');
}

function buildSlicerIni(settings: SliceSettings, printer: PrinterSpec): string {
  const lines: string[] = [
    '# Generated by SliceLab',
    `bed_shape = 0x0,${printer.buildWidthMM}x0,${printer.buildWidthMM}x${printer.buildDepthMM},0x${printer.buildDepthMM}`,
    `display_width = ${printer.buildWidthMM}`,
    `display_height = ${printer.buildDepthMM}`,
    `display_pixels_x = ${printer.resolutionX}`,
    `display_pixels_y = ${printer.resolutionY}`,
    `max_print_height = ${printer.buildHeightMM}`,
    `layer_height = ${settings.layerHeight}`,
    `exposure_time = ${settings.normalExposure}`,
    `initial_exposure_time = ${settings.bottomExposure}`,
    `initial_layer_count = ${settings.bottomLayers}`,
    `faded_layers = ${settings.bottomLayers}`,
    '',
  ];
  return lines.join('\n');
}

async function buildSl1Blob(
  source: LayerSource,
  settings: SliceSettings,
  printer: PrinterSpec,
  onProgress?: ProgressCallback,
): Promise<Blob> {
  const JSZip = (await import('jszip')).default;
  const zip = new JSZip();
  const layerCount = source.kind === 'pixels' ? source.layers.length : source.pngs.length;

  if (source.kind === 'png') {
    for (let i = 0; i < layerCount; i++) {
      onProgress?.(i + 1, layerCount, `Packing layer ${i + 1} / ${layerCount}`);
      const name = String(i).padStart(5, '0');
      zip.file(`${name}.png`, source.pngs[i], { compression: 'STORE' });
    }
  } else {
    const { getSharedPngEncodePool } = await import('../../../png-encode-pool');
    const pool = getSharedPngEncodePool();
    const { resolutionX, resolutionY } = printer;
    const maxInFlight = 8;
    const pngs: Uint8Array[] = new Array(layerCount);
    let dispatched = 0;
    let completed = 0;

    await new Promise<void>((resolve, reject) => {
      const dispatch = (): void => {
        while (dispatched < layerCount && dispatched - completed < maxInFlight) {
          const i = dispatched++;
          const rgba = source.layers[i];
          onProgress?.(completed + 1, layerCount, `Encoding layer ${i + 1} / ${layerCount}`);
          pool
            .encode(rgba, resolutionX, resolutionY)
            .then((png) => {
              pngs[i] = png;
              completed++;
              if (completed === layerCount) resolve();
              else dispatch();
            })
            .catch(reject);
        }
      };
      dispatch();
    });

    for (let i = 0; i < layerCount; i++) {
      const name = String(i).padStart(5, '0');
      zip.file(`${name}.png`, pngs[i], { compression: 'STORE' });
    }
  }

  zip.file('config.ini', buildConfigIni(settings, layerCount));
  zip.file('prusaslicer.ini', buildSlicerIni(settings, printer));

  onProgress?.(layerCount, layerCount, 'Building .sl1 archive...');
  await new Promise((r) => setTimeout(r, 0));

  return zip.generateAsync({ type: 'blob', compression: 'STORE' });
}

export const sl1SliceExporter: SliceExporter = {
  id: 'sl1',
  name: 'SL1 (Prusa)',
  extension: 'sl1',
  isAvailable(): boolean {
    return true;
  },
  async export(
    source: LayerSource,
    settings: SliceSettings,
    printer: PrinterSpec,
    onProgress?: ProgressCallback,
  ): Promise<Blob> {
    return buildSl1Blob(source, settings, printer, onProgress);
  },
};
