/**
 * SL1/SL1S slice exporter for Prusa SL1 / SL1S printers.
 *
 * Format: ZIP archive containing:
 *   - PNG layer images (named NNNNN.png)
 *   - prusaslicer.ini (slicer settings)
 *   - config.ini (print config with exposure, lift, layer count)
 */
import type {
  SliceExporter,
  LayerSource,
  SliceSettings,
  ProgressCallback,
} from '@core/format-registry';
import type { PrinterSpec } from '@core/types';
import {
  addPngFilesToZip,
  getLayerSourceCount,
  resolveLayerSourcePngs,
  yieldToBrowser,
} from './export-helpers';

function buildConfigIni(settings: SliceSettings, layerCount: number): string {
  const lines: string[] = [
    '# Generated by SliceLab',
    `expTime = ${settings.normalExposure}`,
    `expTimeFirst = ${settings.bottomExposure}`,
    `numFade = ${settings.bottomLayers}`,
    `numFast = ${layerCount - settings.bottomLayers}`,
    `numSlow = ${settings.bottomLayers}`,
    `layerHeight = ${settings.layerHeight}`,
    `usedMaterial = ${settings.totalVolumeMm3 !== undefined ? (settings.totalVolumeMm3 / 1000).toFixed(2) : '0'}`,
    `printTime = 0`,
    '',
  ];
  return lines.join('\n');
}

function buildSlicerIni(settings: SliceSettings, printer: PrinterSpec): string {
  const lines: string[] = [
    '# Generated by SliceLab',
    `bed_shape = 0x0,${printer.buildWidthMM}x0,${printer.buildWidthMM}x${printer.buildDepthMM},0x${printer.buildDepthMM}`,
    `display_width = ${printer.buildWidthMM}`,
    `display_height = ${printer.buildDepthMM}`,
    `display_pixels_x = ${printer.resolutionX}`,
    `display_pixels_y = ${printer.resolutionY}`,
    `max_print_height = ${printer.buildHeightMM}`,
    `layer_height = ${settings.layerHeight}`,
    `exposure_time = ${settings.normalExposure}`,
    `initial_exposure_time = ${settings.bottomExposure}`,
    `initial_layer_count = ${settings.bottomLayers}`,
    `faded_layers = ${settings.bottomLayers}`,
    '',
  ];
  return lines.join('\n');
}

async function buildSl1Blob(
  source: LayerSource,
  settings: SliceSettings,
  printer: PrinterSpec,
  onProgress?: ProgressCallback,
): Promise<Blob> {
  const JSZip = (await import('jszip')).default;
  const zip = new JSZip();
  const layerCount = getLayerSourceCount(source);

  if (source.kind === 'png') {
    await addPngFilesToZip(
      zip,
      source.pngs,
      (i) => `${String(i).padStart(5, '0')}.png`,
      onProgress,
    );
  } else {
    const { resolutionX, resolutionY } = printer;
    const pngs = await resolveLayerSourcePngs(source, resolutionX, resolutionY, onProgress);
    await addPngFilesToZip(zip, pngs, (i) => `${String(i).padStart(5, '0')}.png`, onProgress);
  }

  zip.file('config.ini', buildConfigIni(settings, layerCount));
  zip.file('prusaslicer.ini', buildSlicerIni(settings, printer));

  onProgress?.(layerCount, layerCount, 'Building .sl1 archive...');
  await yieldToBrowser();

  return zip.generateAsync({ type: 'blob', compression: 'STORE' }, (metadata) => {
    onProgress?.(
      layerCount,
      layerCount,
      `Building .sl1 archive... ${metadata.percent.toFixed(0)}%`,
    );
  });
}

export const sl1SliceExporter: SliceExporter = {
  id: 'sl1',
  name: 'SL1 (Prusa)',
  extension: 'sl1',
  isAvailable(): boolean {
    return true;
  },
  async export(
    source: LayerSource,
    settings: SliceSettings,
    printer: PrinterSpec,
    onProgress?: ProgressCallback,
  ): Promise<Blob> {
    return buildSl1Blob(source, settings, printer, onProgress);
  },
};
