import type { PrinterSpec } from '@core/types';

export interface PrinterProfile extends PrinterSpec {
  key: string;
  vendor: string;
  image: string;
  description: string;
}

export const PRINTERS: Record<string, PrinterProfile> = {
  'photon-mono': {
    key: 'photon-mono',
    name: 'Anycubic Photon Mono 4K',
    vendor: 'Anycubic',
    image: 'printers/anycubic-photon-mono-4k.jpg',
    description: '6.23" mono LCD, 35μm XY resolution',
    resolutionX: 2560,
    resolutionY: 1620,
    buildWidthMM: 130,
    buildDepthMM: 80,
    buildHeightMM: 165,
  },
  'photon-mono-m5s': {
    key: 'photon-mono-m5s',
    name: 'Anycubic Photon Mono M5s',
    vendor: 'Anycubic',
    image: 'printers/anycubic-photon-mono-m5s.jpg',
    description: '10.1" mono LCD, 19μm XY resolution',
    resolutionX: 11520,
    resolutionY: 5120,
    buildWidthMM: 218.88,
    buildDepthMM: 122.88,
    buildHeightMM: 200,
  },
  'saturn-s': {
    key: 'saturn-s',
    name: 'Elegoo Saturn S',
    vendor: 'Elegoo',
    image: 'printers/elegoo-saturn-s.jpg',
    description: '9.1" 4K mono LCD, ~47μm XY resolution',
    resolutionX: 4098,
    resolutionY: 2560,
    buildWidthMM: 192,
    buildDepthMM: 120,
    buildHeightMM: 200,
  },
  'saturn-4-ultra-16k': {
    key: 'saturn-4-ultra-16k',
    name: 'Elegoo Saturn 4 Ultra 16K',
    vendor: 'Elegoo',
    image: 'printers/elegoo-saturn-4-ultra-16k.jpg',
    description: '10" 16K mono LCD, 14×19μm XY resolution',
    resolutionX: 15120,
    resolutionY: 6230,
    buildWidthMM: 211.68,
    buildDepthMM: 118.37,
    buildHeightMM: 220,
  },
  'mars-5-ultra': {
    key: 'mars-5-ultra',
    name: 'Elegoo Mars 5 Ultra',
    vendor: 'Elegoo',
    image: 'printers/elegoo-mars-5-ultra.jpg',
    description: '7" 9K mono LCD, 18μm XY resolution',
    resolutionX: 8520,
    resolutionY: 4320,
    buildWidthMM: 153.36,
    buildDepthMM: 77.76,
    buildHeightMM: 165,
  },
  'saturn-3-ultra': {
    key: 'saturn-3-ultra',
    name: 'Elegoo Saturn 3 Ultra',
    vendor: 'Elegoo',
    image: 'printers/elegoo-saturn-3-ultra.jpg',
    description: '10" 12K mono LCD, 19×24μm XY resolution',
    resolutionX: 11520,
    resolutionY: 5120,
    buildWidthMM: 218.88,
    buildDepthMM: 122.88,
    buildHeightMM: 260,
  },
  'jupiter-se': {
    key: 'jupiter-se',
    name: 'Elegoo Jupiter SE',
    vendor: 'Elegoo',
    image: 'printers/elegoo-jupiter-se.jpg',
    description: '12.8" 6K mono LCD, 51μm XY resolution',
    resolutionX: 5448,
    resolutionY: 3064,
    buildWidthMM: 277.848,
    buildDepthMM: 156.264,
    buildHeightMM: 300,
  },
  'mars-3': {
    key: 'mars-3',
    name: 'Elegoo Mars 3',
    vendor: 'Elegoo',
    image: 'printers/elegoo-mars-3.jpg',
    description: '6.66" 4K mono LCD, 35μm XY resolution',
    resolutionX: 4098,
    resolutionY: 2560,
    buildWidthMM: 143,
    buildDepthMM: 89.6,
    buildHeightMM: 175,
  },
  'mars-4-ultra': {
    key: 'mars-4-ultra',
    name: 'Elegoo Mars 4 Ultra',
    vendor: 'Elegoo',
    image: 'printers/elegoo-mars-4-ultra.jpg',
    description: '7" 9K mono LCD, 18μm XY resolution',
    resolutionX: 8520,
    resolutionY: 4320,
    buildWidthMM: 153.36,
    buildDepthMM: 77.76,
    buildHeightMM: 165,
  },
  'saturn-2': {
    key: 'saturn-2',
    name: 'Elegoo Saturn 2',
    vendor: 'Elegoo',
    image: 'printers/elegoo-saturn-2.jpg',
    description: '10" 8K mono LCD, 28.5μm XY resolution',
    resolutionX: 7680,
    resolutionY: 4320,
    buildWidthMM: 218.88,
    buildDepthMM: 123.12,
    buildHeightMM: 250,
  },
  'photon-mono-x2': {
    key: 'photon-mono-x2',
    name: 'Anycubic Photon Mono X2',
    vendor: 'Anycubic',
    image: 'printers/anycubic-photon-mono-x2.jpg',
    description: '9.1" 4K+ mono LCD, 48μm XY resolution',
    resolutionX: 4096,
    resolutionY: 2560,
    buildWidthMM: 196.608,
    buildDepthMM: 122.88,
    buildHeightMM: 200,
  },
  'photon-mono-m7-pro': {
    key: 'photon-mono-m7-pro',
    name: 'Anycubic Photon Mono M7 Pro',
    vendor: 'Anycubic',
    image: 'printers/anycubic-photon-mono-m7-pro.jpg',
    description: '10.1" 14K mono LCD, 16.8×24.8μm XY resolution',
    resolutionX: 13320,
    resolutionY: 5120,
    buildWidthMM: 223.776,
    buildDepthMM: 125.952,
    buildHeightMM: 230,
  },
  'photon-mono-m7-max': {
    key: 'photon-mono-m7-max',
    name: 'Anycubic Photon Mono M7 Max',
    vendor: 'Anycubic',
    image: 'printers/anycubic-photon-mono-m7-max.jpg',
    description: '13.6" 7K mono LCD, 46μm XY resolution',
    resolutionX: 6480,
    resolutionY: 3600,
    buildWidthMM: 298.08,
    buildDepthMM: 165.6,
    buildHeightMM: 300,
  },
  'halot-mage-8k': {
    key: 'halot-mage-8k',
    name: 'Creality HALOT-MAGE 8K',
    vendor: 'Creality',
    image: 'printers/creality-halot-mage-8k.jpg',
    description: '10.3" 8K mono LCD, 29.7μm XY resolution',
    resolutionX: 7680,
    resolutionY: 4320,
    buildWidthMM: 228,
    buildDepthMM: 128,
    buildHeightMM: 230,
  },
  'uniformation-gktwo': {
    key: 'uniformation-gktwo',
    name: 'UniFormation GKtwo',
    vendor: 'UniFormation',
    image: 'printers/uniformation-gktwo.png',
    description: '10.3" 8K mono LCD, 29.7μm XY resolution',
    resolutionX: 7680,
    resolutionY: 4320,
    buildWidthMM: 228,
    buildDepthMM: 128,
    buildHeightMM: 245,
  },
  'sonic-mega-8k-s': {
    key: 'sonic-mega-8k-s',
    name: 'Phrozen Sonic Mega 8K S',
    vendor: 'Phrozen',
    image: 'printers/phrozen-sonic-mega-8k-s.png',
    description: '15" 8K mono LCD, 43μm XY resolution',
    resolutionX: 7680,
    resolutionY: 4320,
    buildWidthMM: 330.24,
    buildDepthMM: 185.76,
    buildHeightMM: 300,
  },
  'sonic-mini-8k': {
    key: 'sonic-mini-8k',
    name: 'Phrozen Sonic Mini 8K',
    vendor: 'Phrozen',
    image: 'printers/phrozen-sonic-mini-8k.png',
    description: '7.1" 8K mono LCD, 22μm XY resolution',
    resolutionX: 7500,
    resolutionY: 3300,
    buildWidthMM: 165,
    buildDepthMM: 72,
    buildHeightMM: 180,
  },
  'sonic-mighty-8k': {
    key: 'sonic-mighty-8k',
    name: 'Phrozen Sonic Mighty 8K',
    vendor: 'Phrozen',
    image: 'printers/phrozen-sonic-mighty-8k.png',
    description: '10" 8K mono LCD, 29μm XY resolution',
    resolutionX: 7680,
    resolutionY: 4320,
    buildWidthMM: 223,
    buildDepthMM: 126,
    buildHeightMM: 235,
  },
  'sl1s-speed': {
    key: 'sl1s-speed',
    name: 'Prusa SL1S Speed',
    vendor: 'Prusa',
    image: 'printers/prusa-sl1s-speed.jpg',
    description: '5.96" mSLA, 50μm XY resolution',
    resolutionX: 2560,
    resolutionY: 1620,
    buildWidthMM: 127,
    buildDepthMM: 80,
    buildHeightMM: 150,
  },
  'form-4': {
    key: 'form-4',
    name: 'Formlabs Form 4',
    vendor: 'Formlabs',
    image: 'printers/formlabs-form-4.jpg',
    description: 'Low Force Display, 50μm XY resolution',
    resolutionX: 4000,
    resolutionY: 2500,
    buildWidthMM: 200,
    buildDepthMM: 125,
    buildHeightMM: 210,
  },
};

export const DEFAULT_PRINTER_KEY = 'photon-mono';

export function getPrinter(key: string): PrinterProfile | undefined {
  return PRINTERS[key];
}

export function getAllPrinterKeys(): string[] {
  return Object.keys(PRINTERS);
}

export function getPrintersByVendor(vendor: string): PrinterProfile[] {
  return Object.values(PRINTERS).filter((p) => p.vendor === vendor);
}

export function getAllVendors(): string[] {
  return [...new Set(Object.values(PRINTERS).map((p) => p.vendor))];
}

export function computePixelPitch(printer: PrinterProfile): { x: number; y: number } {
  return {
    x: printer.buildWidthMM / printer.resolutionX,
    y: printer.buildDepthMM / printer.resolutionY,
  };
}
