import type { ResinMaterial } from '@core/types';

export const RESIN_MATERIALS: readonly ResinMaterial[] = [
  {
    id: 'siraya-fast-navy-grey',
    brand: 'Siraya Tech',
    product: 'Fast ABS-Like',
    colorName: 'Navy Grey',
    swatch: '#4f6170',
    color: 0x4f6170,
    opacity: 0.96,
    roughness: 0.52,
    metalness: 0.0,
    transmission: 0.0,
    ior: 1.5,
    description: 'Opaque cool grey, matte hobby resin',
    sourceUrl: 'https://siraya.tech/products/fast-abs-like-grey',
  },
  {
    id: 'siraya-fast-creamy',
    brand: 'Siraya Tech',
    product: 'Fast ABS-Like',
    colorName: 'Creamy',
    swatch: '#d8c7a8',
    color: 0xd8c7a8,
    opacity: 0.97,
    roughness: 0.54,
    metalness: 0.0,
    transmission: 0.0,
    ior: 1.5,
    description: 'Opaque warm beige, low-sheen detail resin',
    sourceUrl: 'https://siraya.tech/products/fast-abs-like-grey',
  },
  {
    id: 'siraya-fast-white',
    brand: 'Siraya Tech',
    product: 'Fast ABS-Like',
    colorName: 'White',
    swatch: '#f2f0e7',
    color: 0xf2f0e7,
    opacity: 0.98,
    roughness: 0.58,
    metalness: 0.0,
    transmission: 0.0,
    ior: 1.5,
    description: 'Opaque off-white, bright matte preview',
    sourceUrl: 'https://siraya.tech/products/fast-abs-like-grey',
  },
  {
    id: 'siraya-fast-smoky-black',
    brand: 'Siraya Tech',
    product: 'Fast ABS-Like',
    colorName: 'Smoky Black',
    swatch: '#1f2428',
    color: 0x1f2428,
    opacity: 0.82,
    roughness: 0.38,
    metalness: 0.0,
    transmission: 0.05,
    ior: 1.52,
    description: 'Tinted black with mild translucency',
    sourceUrl: 'https://siraya.tech/products/fast-abs-like-grey',
  },
  {
    id: 'siraya-tenacious-clear',
    brand: 'Siraya Tech',
    product: 'Tenacious 65D',
    colorName: 'Clear',
    swatch: '#dbe9ef',
    color: 0xdbe9ef,
    opacity: 0.62,
    roughness: 0.22,
    metalness: 0.0,
    transmission: 0.32,
    ior: 1.54,
    description: 'Flexible clear resin, denser transparent preview',
    sourceUrl: 'https://siraya.tech/products/tenacious-resin-flexible-resin',
  },
  {
    id: 'anycubic-standard-v2-grey',
    brand: 'Anycubic',
    product: 'Standard Resin V2',
    colorName: 'Grey',
    swatch: '#7e93a7',
    color: 0x7e93a7,
    opacity: 0.95,
    roughness: 0.48,
    metalness: 0.0,
    transmission: 0.0,
    ior: 1.5,
    description: 'Official grey tone, semi-matte standard resin',
    sourceUrl: 'https://store.anycubic.com/products/standard-resin-v2-mix-match',
  },
  {
    id: 'anycubic-standard-v2-white',
    brand: 'Anycubic',
    product: 'Standard Resin V2',
    colorName: 'White',
    swatch: '#f4f2ea',
    color: 0xf4f2ea,
    opacity: 0.98,
    roughness: 0.5,
    metalness: 0.0,
    transmission: 0.0,
    ior: 1.5,
    description: 'Opaque white standard resin',
    sourceUrl: 'https://store.anycubic.com/products/standard-resin-v2-mix-match',
  },
  {
    id: 'anycubic-standard-v2-black',
    brand: 'Anycubic',
    product: 'Standard Resin V2',
    colorName: 'Black',
    swatch: '#242322',
    color: 0x242322,
    opacity: 0.98,
    roughness: 0.42,
    metalness: 0.0,
    transmission: 0.0,
    ior: 1.5,
    description: 'Opaque black standard resin',
    sourceUrl: 'https://store.anycubic.com/products/standard-resin-v2-mix-match',
  },
  {
    id: 'anycubic-standard-v2-beige',
    brand: 'Anycubic',
    product: 'Standard Resin V2',
    colorName: 'Beige',
    swatch: '#d1b48d',
    color: 0xd1b48d,
    opacity: 0.97,
    roughness: 0.52,
    metalness: 0.0,
    transmission: 0.0,
    ior: 1.5,
    description: 'Opaque beige standard resin',
    sourceUrl: 'https://store.anycubic.com/products/standard-resin-v2-mix-match',
  },
  {
    id: 'anycubic-standard-clear',
    brand: 'Anycubic',
    product: 'Standard Resin',
    colorName: 'Clear',
    swatch: '#e1edf2',
    color: 0xe1edf2,
    opacity: 0.58,
    roughness: 0.24,
    metalness: 0.0,
    transmission: 0.35,
    ior: 1.54,
    description: 'Clear resin with stronger surface visibility',
    sourceUrl: 'https://store.anycubic.com/products/colored-uv-resin',
  },
  {
    id: 'anycubic-standard-clear-green',
    brand: 'Anycubic',
    product: 'Standard Resin',
    colorName: 'Clear Green',
    swatch: '#75b987',
    color: 0x75b987,
    opacity: 0.62,
    roughness: 0.25,
    metalness: 0.0,
    transmission: 0.3,
    ior: 1.53,
    description: 'Green-tinted clear resin with readable silhouettes',
    sourceUrl: 'https://store.anycubic.com/products/colored-uv-resin',
  },
  {
    id: 'anycubic-standard-clear-red',
    brand: 'Anycubic',
    product: 'Standard Resin',
    colorName: 'Clear Red',
    swatch: '#d46a66',
    color: 0xd46a66,
    opacity: 0.62,
    roughness: 0.25,
    metalness: 0.0,
    transmission: 0.3,
    ior: 1.53,
    description: 'Red-tinted clear resin with readable silhouettes',
    sourceUrl: 'https://store.anycubic.com/products/colored-uv-resin',
  },
  {
    id: 'elegoo-abs-like-grey',
    brand: 'ELEGOO',
    product: 'ABS-Like',
    colorName: 'Grey',
    swatch: '#8f9291',
    color: 0x8f9291,
    opacity: 0.96,
    roughness: 0.46,
    metalness: 0.0,
    transmission: 0.0,
    ior: 1.5,
    description: 'Opaque neutral grey ABS-like resin',
    sourceUrl: 'https://www.elegoo.com/en-gb/products/abs-like-resin-1kg',
  },
  {
    id: 'elegoo-abs-like-white',
    brand: 'ELEGOO',
    product: 'ABS-Like',
    colorName: 'White',
    swatch: '#efeee8',
    color: 0xefeee8,
    opacity: 0.98,
    roughness: 0.5,
    metalness: 0.0,
    transmission: 0.0,
    ior: 1.5,
    description: 'Opaque white ABS-like resin',
    sourceUrl: 'https://www.elegoo.com/en-gb/products/abs-like-resin-1kg',
  },
  {
    id: 'elegoo-abs-like-beige',
    brand: 'ELEGOO',
    product: 'ABS-Like',
    colorName: 'Beige',
    swatch: '#cdb083',
    color: 0xcdb083,
    opacity: 0.97,
    roughness: 0.48,
    metalness: 0.0,
    transmission: 0.0,
    ior: 1.5,
    description: 'Opaque beige ABS-like resin',
    sourceUrl: 'https://www.elegoo.com/en-gb/products/abs-like-resin-1kg',
  },
  {
    id: 'elegoo-abs-like-black',
    brand: 'ELEGOO',
    product: 'ABS-Like',
    colorName: 'Black',
    swatch: '#202123',
    color: 0x202123,
    opacity: 0.98,
    roughness: 0.42,
    metalness: 0.0,
    transmission: 0.0,
    ior: 1.5,
    description: 'Opaque black ABS-like resin',
    sourceUrl: 'https://www.elegoo.com/en-gb/products/abs-like-resin-1kg',
  },
  {
    id: 'elegoo-abs-like-clear-blue',
    brand: 'ELEGOO',
    product: 'ABS-Like',
    colorName: 'Clear Blue',
    swatch: '#59a7c9',
    color: 0x59a7c9,
    opacity: 0.64,
    roughness: 0.26,
    metalness: 0.0,
    transmission: 0.28,
    ior: 1.53,
    description: 'Blue-tinted transparent resin with stronger geometry cues',
    sourceUrl: 'https://www.elegoo.com/en-gb/products/abs-like-resin-1kg',
  },
  {
    id: 'elegoo-standard-translucent',
    brand: 'ELEGOO',
    product: 'Standard',
    colorName: 'Translucent',
    swatch: '#f0e6cd',
    color: 0xf0e6cd,
    opacity: 0.62,
    roughness: 0.3,
    metalness: 0.0,
    transmission: 0.3,
    ior: 1.53,
    description: 'Warm translucent standard resin with denser preview',
    sourceUrl:
      'https://us.elegoo.com/collections/resin-1-2kg-buy-more-save-more/products/elegoo-standard-resin',
  },
  {
    id: 'elegoo-standard-clear-red',
    brand: 'ELEGOO',
    product: 'Standard',
    colorName: 'Clear Red',
    swatch: '#d85f62',
    color: 0xd85f62,
    opacity: 0.63,
    roughness: 0.28,
    metalness: 0.0,
    transmission: 0.28,
    ior: 1.53,
    description: 'Red translucent standard resin',
    sourceUrl:
      'https://us.elegoo.com/collections/resin-1-2kg-buy-more-save-more/products/elegoo-standard-resin',
  },
  {
    id: 'elegoo-standard-clear-green',
    brand: 'ELEGOO',
    product: 'Standard',
    colorName: 'Clear Green',
    swatch: '#68af79',
    color: 0x68af79,
    opacity: 0.63,
    roughness: 0.28,
    metalness: 0.0,
    transmission: 0.28,
    ior: 1.53,
    description: 'Green translucent standard resin',
    sourceUrl:
      'https://us.elegoo.com/collections/resin-1-2kg-buy-more-save-more/products/elegoo-standard-resin',
  },
] as const;

export const DEFAULT_MATERIAL_ID = 'siraya-fast-navy-grey';

export function getMaterialById(id: string): ResinMaterial | undefined {
  return RESIN_MATERIALS.find((m) => m.id === id);
}

export function getMaterialsByBrand(brand: string): ResinMaterial[] {
  return RESIN_MATERIALS.filter((m) => m.brand === brand);
}

export function getAllBrands(): string[] {
  return [...new Set(RESIN_MATERIALS.map((m) => m.brand))];
}
