export const RESIN_MATERIALS = [
  {
    id: 'siraya-fast-navy-grey',
    brand: 'Siraya Tech',
    product: 'Fast ABS-Like',
    colorName: 'Navy Grey',
    swatch: '#4f6170',
    color: 0x4f6170,
    opacity: 0.96,
    roughness: 0.52,
    metalness: 0.0,
    transmission: 0.0,
    ior: 1.5,
    description: 'Opaque cool grey, matte hobby resin',
    sourceUrl: 'https://siraya.tech/products/fast-abs-like-grey',
  },
  {
    id: 'siraya-fast-smoky-black',
    brand: 'Siraya Tech',
    product: 'Fast ABS-Like',
    colorName: 'Smoky Black',
    swatch: '#1f2428',
    color: 0x1f2428,
    opacity: 0.72,
    roughness: 0.38,
    metalness: 0.0,
    transmission: 0.1,
    ior: 1.52,
    description: 'Tinted black with mild translucency',
    sourceUrl: 'https://siraya.tech/products/fast-abs-like-grey',
  },
  {
    id: 'siraya-tenacious-clear',
    brand: 'Siraya Tech',
    product: 'Tenacious 65D',
    colorName: 'Clear',
    swatch: '#dbe9ef',
    color: 0xdbe9ef,
    opacity: 0.36,
    roughness: 0.18,
    metalness: 0.0,
    transmission: 0.62,
    ior: 1.54,
    description: 'Flexible clear resin, glossy transparent look',
    sourceUrl: 'https://siraya.tech/products/tenacious-resin-flexible-resin',
  },
  {
    id: 'anycubic-standard-v2-grey',
    brand: 'Anycubic',
    product: 'Standard Resin V2',
    colorName: 'Grey',
    swatch: '#7e93a7',
    color: 0x7e93a7,
    opacity: 0.95,
    roughness: 0.48,
    metalness: 0.0,
    transmission: 0.0,
    ior: 1.5,
    description: 'Official grey tone, semi-matte standard resin',
    sourceUrl: 'https://store.anycubic.com/products/standard-resin-v2-mix-match',
  },
  {
    id: 'anycubic-standard-clear',
    brand: 'Anycubic',
    product: 'Standard Resin',
    colorName: 'Clear',
    swatch: '#e1edf2',
    color: 0xe1edf2,
    opacity: 0.32,
    roughness: 0.2,
    metalness: 0.0,
    transmission: 0.7,
    ior: 1.54,
    description: 'Clear option with high light bleed preview',
    sourceUrl: 'https://store.anycubic.com/products/colored-uv-resin',
  },
  {
    id: 'elegoo-abs-like-grey',
    brand: 'ELEGOO',
    product: 'ABS-Like',
    colorName: 'Grey',
    swatch: '#8f9291',
    color: 0x8f9291,
    opacity: 0.96,
    roughness: 0.46,
    metalness: 0.0,
    transmission: 0.0,
    ior: 1.5,
    description: 'Opaque neutral grey ABS-like resin',
    sourceUrl: 'https://www.elegoo.com/en-gb/products/abs-like-resin-1kg',
  },
  {
    id: 'elegoo-abs-like-clear-blue',
    brand: 'ELEGOO',
    product: 'ABS-Like',
    colorName: 'Clear Blue',
    swatch: '#59a7c9',
    color: 0x59a7c9,
    opacity: 0.42,
    roughness: 0.24,
    metalness: 0.0,
    transmission: 0.52,
    ior: 1.53,
    description: 'Blue-tinted transparent ABS-like resin',
    sourceUrl: 'https://www.elegoo.com/en-gb/products/abs-like-resin-1kg',
  },
  {
    id: 'elegoo-standard-translucent',
    brand: 'ELEGOO',
    product: 'Standard',
    colorName: 'Translucent',
    swatch: '#f0e6cd',
    color: 0xf0e6cd,
    opacity: 0.4,
    roughness: 0.28,
    metalness: 0.0,
    transmission: 0.58,
    ior: 1.53,
    description: 'Warm translucent standard resin',
    sourceUrl: 'https://us.elegoo.com/collections/resin-1-2kg-buy-more-save-more/products/elegoo-standard-resin',
  },
];

export const DEFAULT_RESIN_MATERIAL_ID = 'siraya-fast-navy-grey';
